# Generated by Django 5.0.1 on 2024-01-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('City', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QueryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('City', models.CharField(max_length=200)),
            ],
        ),
    ]
