# Generated by Django 5.0.1 on 2024-01-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_querystore_city_remove_querystore_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='querystore',
            name='OrdefrId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
